spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/smarttask}
spring.datasource.username=${DB_USERNAME:smarttask}
spring.datasource.password=${DB_PASSWORD:smarttask}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
springdoc.swagger-ui.path=/swagger-ui.html
server.port=${PORT:8080}
